# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rexml/all/rexml.rbi
#
# rexml-3.4.4

module REXML
end
class REXML::ParseException < RuntimeError
end
class REXML::UndefinedNamespaceException < REXML::ParseException
end
module REXML::Security
end
module REXML::Encoding
end
class REXML::SourceFactory
end
class REXML::Source
  include REXML::Encoding
end
module REXML::Source::Private
end
class REXML::IOSource < REXML::Source
end
module REXML::Parsers
end
class REXML::Parsers::BaseParser
end
module REXML::Parsers::BaseParser::Private
end
module REXML::XMLTokens
end
