# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/site_ruby/all/site_ruby.rbi
#
# site_ruby-3.3.0

module Bundler
end
module Bundler::Plugin
end
module Bundler::Plugin::Events
  def self.define(const, event); end
  def self.defined_event?(event); end
  def self.reset; end
end
class Bundler::Plugin::Index
  def command_plugin(command); end
  def commands; end
  def global_index_file; end
  def hook_plugins(event); end
  def index_file; end
  def initialize; end
  def installed?(name); end
  def installed_in_plugin_root?(name); end
  def installed_plugins; end
  def load_index(index_file, global = nil); end
  def load_paths(name); end
  def local_index_file; end
  def plugin_commands(plugin); end
  def plugin_path(name); end
  def register_plugin(name, path, load_paths, commands, sources, hooks); end
  def save_index; end
  def source?(source); end
  def source_plugin(name); end
  def unregister_plugin(name); end
end
class Bundler::Plugin::Index::CommandConflict < Bundler::PluginError
  def initialize(plugin, commands); end
end
class Bundler::Plugin::Index::SourceConflict < Bundler::PluginError
  def initialize(plugin, sources); end
end
