# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/yard-solargraph/all/yard-solargraph.rbi
#
# yard-solargraph-0.1.0

module YARD
end
module YARD::Solargraph
end
class YARD::Tags::Library
  def generic_tag(text); end
  def yieldreceiver_tag(text); end
end
